//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinal1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARTICLE
    {
        public string ID_AR { get; set; }
        public string NAME_AR { get; set; }
        public string IMG { get; set; }
        public string NDTT { get; set; }
        public Nullable<System.DateTime> DATE_SUB { get; set; }
        public string LOAITIN { get; set; }
        public string ND { get; set; }
        public string ACCOUNT { get; set; }
        public Nullable<bool> DADUYET { get; set; }
    
        public virtual ACCOUNT ACCOUNT1 { get; set; }
    }
}
