//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinal1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INVENTORY
    {
        public string ID_PR { get; set; }
        public int ID_L { get; set; }
        public string ID_BR { get; set; }
        public Nullable<int> NUMBER_IVT { get; set; }
        public Nullable<int> INVENTORY1 { get; set; }
    
        public virtual BRAND BRAND { get; set; }
        public virtual LOAISP LOAISP { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
