//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinal1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDER()
        {
            this.ORDER_DETAILS = new HashSet<ORDER_DETAILS>();
        }
    
        public string NUMBER_OR { get; set; }
        public string ID_CT { get; set; }
        public string ACCOUNT { get; set; }
        public Nullable<System.DateTime> DATE_OR { get; set; }
        public Nullable<bool> ACTIVATED { get; set; }
        public Nullable<System.DateTime> DATE_DEL { get; set; }
        public string HOME_OR { get; set; }
        public string NOTE { get; set; }
    
        public virtual ACCOUNT ACCOUNT1 { get; set; }
        public virtual CUSTOMER CUSTOMER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_DETAILS> ORDER_DETAILS { get; set; }
    }
}
