//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinal1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_DETAILS
    {
        public string NUMBER_OR { get; set; }
        public string ID_PR { get; set; }
        public Nullable<int> AMOUNT { get; set; }
        public Nullable<long> PRICE { get; set; }
        public Nullable<long> SALE { get; set; }
    
        public virtual PRODUCT PRODUCT { get; set; }
        public virtual ORDER ORDER { get; set; }
    }
}
