//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFinal1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.ORDER_DETAILS = new HashSet<ORDER_DETAILS>();
            this.INVENTORies = new HashSet<INVENTORY>();
        }
    
        public string ID_PR { get; set; }
        public string NAME_PR { get; set; }
        public string IMG { get; set; }
        public string NDTT { get; set; }
        public Nullable<System.DateTime> DATE_SUB { get; set; }
        public int ID_L { get; set; }
        public string ND { get; set; }
        public string ACCOUNT { get; set; }
        public string DVTINH { get; set; }
        public Nullable<bool> DADUYET { get; set; }
        public Nullable<int> PRICE { get; set; }
        public Nullable<int> SALE { get; set; }
        public string PRODUCER { get; set; }
        public string NAME_L { get; set; }
        public string ID_BR { get; set; }
    
        public virtual ACCOUNT ACCOUNT1 { get; set; }
        public virtual LOAISP LOAISP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDER_DETAILS> ORDER_DETAILS { get; set; }
        public virtual BRAND BRAND { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVENTORY> INVENTORies { get; set; }
    }
}
